{
 "title": "UMBS AmeriFlux stats",
 "description": "a real-time viz for AmeriFlux sensor data output at UMBS AmeriFlux core site",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Header", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instructions",
   "type": "text",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 1 },
   "options": {
    "content": "- drag over a zone to zoom in\n- click on names in the legend to view the trendline alone\n- only view one dropdown at a time so that data loads faster    \n- click the i in the top left corner of a graph for a description of where the data are from and, if averaged, over what time period\n- if graph says, \"data does not have a time field\", then the selected time range does not contain any data for that query"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "options": {
    "content": "- data began uploading on July 6th, so no data are older\n- queries only go back as far as the time frame specified in the top right\n- all data are retained 7 days, except soil data which is retained 30 days\n- GitHub code (requires GitHub account and UMBS org access): https://github.com/um-biological-station/AmeriFlux-dashboard-sync"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature and RH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Air Temperature by Height",
     "type": "timeseries",
     "description": "sample air temperature at 46m, 34m, 15m; 10-minute average air temperature at 3m",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Temp_46m\"\n  )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Temp_34m\"\n  )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Temp_15m\"\n  )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Temp_avg_3m\"\n  )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Relative Humidity by Height",
     "type": "timeseries",
     "description": "RH measured at 46m, 34m, 15m; 10-second average RH at 3m",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"RH_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"RH_34m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"RH_15m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"RH_avg_3m\"\n  )"
      }
     ]
    },
    {
     "title": "Sonic Air Temperature by Height",
     "type": "timeseries",
     "description": "sonic temperature at 46m, 34m",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Sonic_temp_46m\"\n  )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Sonic_temp_34m\"\n  )",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Wind Speed by Height",
     "type": "timeseries",
     "description": "5-minute average wind vector speed calculated from directional sonic wind speed at 46m, 34m; anemometer wind speed at 46m",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"U_wind_speed_46m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"U_wind_speed_34m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Wind_speed_46m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "[CO2] + [H2O]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CO2 Concentration by Height",
     "type": "timeseries",
     "description": "CO2 concentration sampled at 46m, 34m, 22m, 7m, 3m, 0m; 0-22m sensors only record in rotation (one at a time)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_34m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_22m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_7m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_3m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_0m\"\n  )"
      }
     ]
    },
    {
     "title": "Average CO2 Concentration by Height",
     "type": "timeseries",
     "description": "10-minute average CO2 concentration sampled at 46m, 34m, 22m, 7m, 3m, 0m; 0-22m sensors only record in rotation (one at a time)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_46m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_34m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_22m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_7m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_3m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_0m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      }
     ]
    },
    {
     "title": "H2O Concentration by Height",
     "type": "timeseries",
     "description": "H2O concentration sampled at 46m, 34m, 22m, 7m, 3m, 0m; 0-22m sensors only record in rotation (one at a time)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ppt" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_34m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_22m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_7m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_3m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_0m\"\n  )"
      }
     ]
    },
    {
     "title": "Average H2O Concentration by Height",
     "type": "timeseries",
     "description": "10-minute average H2O concentration sampled at 46m, 34m, 22m, 7m, 3m, 0m; 0-22m sensors only record in rotation (one at a time)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ppt" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_46m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_34m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_22m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_7m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_3m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"H2O_0m\"\n  )\n  |> aggregateWindow(\n    every: 10m,\n    fn: mean\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "46m IRGA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CO2 vs Vertical Wind Speed",
     "type": "graph",
     "description": "46m CO2 concentration 10 hz samples vs sonic Uz wind speed 1-minute averages",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ppm", "label": "CO2 Concentration" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Uz_46m\"\n  )\n  |> aggregateWindow(\n    every: 1m,\n    fn: mean\n  )"
      }
     ]
    },
    {
     "title": "IRGA cell temperature",
     "type": "timeseries",
     "description": "46m IRGA cell temperature output in mV",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "mvolt" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Cell_temp_46m\"\n  )"
      }
     ]
    },
    {
     "title": "IRGA cell pressure",
     "type": "timeseries",
     "description": "46m IRGA cell pressure output in mV",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "mvolt" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Cell_pressure_46m\"\n  )\n"
      }
     ]
    }
   ]
  },
  {
   "title": "34m IRGA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CO2 vs Vertical Wind Speed",
     "type": "graph",
     "description": "34m CO2 concentration 10 hz samples vs sonic Uz wind speed 1-minute averages",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ppm", "label": "CO2 Concentration" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"CO2_34m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Uz_34m\"\n  )\n  |> aggregateWindow(\n    every: 1m,\n    fn: mean\n  )"
      }
     ]
    },
    {
     "title": "IRGA cell temperature",
     "type": "timeseries",
     "description": "34m IRGA cell temperature output in mV",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "mvolt" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Cell_temp_34m\"\n  )"
      }
     ]
    },
    {
     "title": "IRGA cell pressure",
     "type": "timeseries",
     "description": "34m IRGA cell pressure output in mV",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "mvolt" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Cell_pressure_34m\"\n  )\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Radiation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solar Radiation",
     "type": "timeseries",
     "description": "Kipp & Zonen CNR1 radiation metrics measured at 46m",
     "gridPos": { "h": 16, "w": 9, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Wm2" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Incident_solar_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Reflected_solar_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Net_radiation_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Incident_far_red_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Outgoing_far_red_46m\"\n  )"
      }
     ]
    },
    {
     "title": "PPFD",
     "type": "timeseries",
     "description": "LI-COR uncorrected PPFD, BF% Sun Shine sensor diffuse and total PPFD, all in micromoles per square meter per second",
     "gridPos": { "h": 16, "w": 9, "x": 9, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"PPFD_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Diffuse_PPFD_46m\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Total_PPFD_46m\"\n  )"
      }
     ]
    },
    {
     "title": "Downward PAR",
     "type": "stat",
     "description": "LI-COR downward-facing PAR measured at 37m, in micromoles per square meter per second, red if last reported value is below 0.1",
     "gridPos": { "h": 7, "w": 5, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_atmospheric\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fastdata\" and\n    r._field == \"Downward_PAR_37m\"\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "Soil",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Soil Temperature by Depth",
     "type": "timeseries",
     "description": "Soil temperature measured at 5 different depths, averaged over 3 stations per depth",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field =~ /Soil_temp_2cm/\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field =~ /Soil_temp_7.5cm/\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field =~ /Soil_temp_20cm/\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field =~ /Soil_temp_50cm/\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field =~ /Soil_temp_1m/\n  )"
      }
     ]
    },
    {
     "title": "Soil Moisture by Depth",
     "type": "timeseries",
     "description": "Soil moisture measured at 3 different depths and 3 times over a range of depths (3 horizontal sensors and 3 vertical sensors), all in percent volume",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_moisture_5cm\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_moisture_15cm\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_moisture_30cm\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_moisture_0-30cm_1\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_moisture_0-30cm_2\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_moisture_0-30cm_3\"\n  )"
      }
     ]
    },
    {
     "title": "Soil Temperature at Station 1",
     "type": "timeseries",
     "description": "30-minute average soil temperatures at 5 depths, all measured at station 1",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_2cm_st1\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_7.5cm_st1\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_20cm_st1\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_50cm_st1\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_1m_st1\"\n  )"
      }
     ]
    },
    {
     "title": "Soil Temperature at Station 2",
     "type": "timeseries",
     "description": "30-minute average soil temperatures at 5 depths, all measured at station 2",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_2cm_st2\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_7.5cm_st2\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_20cm_st2\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_50cm_st2\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_1m_st2\"\n  )"
      }
     ]
    },
    {
     "title": "Soil Temperature at Station 3",
     "type": "timeseries",
     "description": "30-minute average soil temperatures at 5 depths, all measured at station 3",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_2cm_st3\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_7.5cm_st3\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_20cm_st3\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_50cm_st3\"\n  )"
      },
      {
       "query": "from(bucket: \"ameriflux_soil\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"slowdata\" and\n    r._field == \"Soil_temp_1m_st3\"\n  )"
      }
     ]
    }
   ]
  }
 ]
}